### PR TITLE
Feat/exec all

### PR DESCRIPTION
**Pull request by mabmayer**
added support for the ExecAll call.

### CODE REVIEW

**Review by SimoneLazzaris — APPROVED** [review]
Looks good. What is coverage after merging?

**Comment by mabmayer** [comment]
Good point.

**Comment by mabmayer** [comment]
@SimoneLazzaris I reworked the tests. There are some parts in typeconf.py, which are not fully covered.

**Comment by ufierro** [comment]
LGTM

**Review by ufierro — APPROVED** [review]

**Comment by ufierro** [comment]
I did some cleaning up to make tests easier to maintain, @SimoneLazzaris feel free to comment or discard commits following up to this point if something seems off otherwise we can proceed merging

**Comment by mabmayer** [comment]
Thx @ufierro for the fixtures!

**Pull request merged**
